package ast

import "github.com/jvbenetti/zenith-lang.git/token"

// Node is the base interface for all nodes in the AST. Every node in our AST must have a TokenLiteral() method.
// This is only for debugging purposes, so we can print which token generated this node.
type Node interface {
	TokenLiteral() string
}

// Statement is a node that does not produce a value (e.g., let x = 5;)
type Statement interface {
	Node
	statementNode() // Dummy method to distinguish Statement from Expression
}

// Expression is a node that produces a value (e.g., 5 + 5)
type Expression interface {
	Node
	expressionNode() // Dummy method to distinguish Expression from Statement
}

// Program is the ROOT node of our entire tree.
// A program in Zenith is simply a list of Statements (declarations) being executed one after another.
type Program struct {
	Statements []Statement
}

func (p *Program) TokenLiteral() string {
	if len(p.Statements) > 0 {
		return p.Statements[0].TokenLiteral()
	}
	return ""
}

// Identifier is the var name (ex: the "x" in "let x = 5")
// Note: In languages, the variable name is considered an Expression,
// because when you type just "x", it produces the value stored in the variable.
type Identifier struct {
	Token token.Token // The IDENT token generated by the lexer
	Value string      // The actual name of the variable (e.g., "x")
}

func (i *Identifier) expressionNode()      {}
func (i *Identifier) TokenLiteral() string { return i.Token.Literal }

// LetStatement represents the entire line: let <Name> <Type> = <Value>;
type LetStatement struct {
	Token token.Token // The token token.LET
	Name  *Identifier // The name of the variable (e.g., "x")

	// As you implemented typing (e.g., int64), we need to store this in the tree!
	ValueType *Identifier // (Optional for now) Will hold the "int64", "string", etc.

	Value Expression // The expression that generates the value (can be "5", or "2 + 3", or a function call)
}

func (ls *LetStatement) statementNode()       {}
func (ls *LetStatement) TokenLiteral() string { return ls.Token.Literal }
